name: docker-install CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu:18.04
          - ubuntu:20.04
          - centos:7
        version:
          - 19.03
          - 18.09

    steps:
    - uses: actions/checkout@v2
    - name: Check distribution
      run: TEST_IMAGE=${{ matrix.os }} VERSION=${{ matrix.version }} make test